universe = local
executable = /home/spxfp1/opt/lalsuite/lalinference_o2_phenomHM/bin/gw_data_find
arguments = " --observatory $(macroobservatory) --url-type file --gps-start-time $(macrogpsstarttime) --gps-end-time $(macrogpsendtime) --output $(macrooutput) --lal-cache --type $(macrotype) "
accounting_group = ligo.sim.o2.cbc.pe.lalinference
accounting_group_user = rhys.green
getenv = True
log = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_25_mode_PhenomPv2_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/lalinference_pipeline-b59b5f42-6ae6-11e7-a4fe-002590fc7bee.log
error = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_25_mode_PhenomPv2_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/log/datafind-$(macroobservatory)-$(macrotype)-$(macrogpsstarttime)-$(macrogpsendtime)-$(cluster)-$(process).err
output = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_25_mode_PhenomPv2_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/log/datafind-$(macroobservatory)-$(macrotype)-$(macrogpsstarttime)-$(macrogpsendtime)-$(cluster)-$(process).out
notification = never
queue 1
