universe = vanilla
executable = /software/physics/ligo/spack/000/linux-redhat6-x86_64/gcc-5.4.0/ldg/pickxdy/bin/run_sky_area
arguments = " --fitsoutname $(macrofitsoutname) --objid $(macroobjid) --samples $(macrosamples) --outdir $(macrooutdir) "
getenv = True
accounting_group_user = rhys.green
accounting_group = ligo.sim.o2.cbc.pe.lalinference
log = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_25_mode_PhenomPv2_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/lalinference_pipeline-b59b5f42-6ae6-11e7-a4fe-002590fc7bee.log
error = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_25_mode_PhenomPv2_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/log/skyarea-$(cluster)-$(process).err
output = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_25_mode_PhenomPv2_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/log/skyarea-$(cluster)-$(process).out
notification = never
queue 1
