universe = vanilla
executable = /home/spxfp1/opt/lalsuite/lalinference_o2_phenomHM/bin/lalapps_nest2pos
arguments = " --pos $(macropos) $(macroargument0) $(macroargument1) $(macroargument2) $(macroargument3) "
getenv = True
accounting_group = ligo.sim.o2.cbc.pe.lalinference
log = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_50_mode_PhenomPv2_inc_0.0_M90/PM90/lalinferencenest/IMRPhenomDthreePointFivePN/lalinference_pipeline-1413ca3e-6d29-11e7-a3af-002590fc7bee.log
error = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_50_mode_PhenomPv2_inc_0.0_M90/PM90/lalinferencenest/IMRPhenomDthreePointFivePN/log/merge-$(cluster)-$(process).err
output = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_50_mode_PhenomPv2_inc_0.0_M90/PM90/lalinferencenest/IMRPhenomDthreePointFivePN/log/merge-$(cluster)-$(process).out
notification = never
queue 1
