universe = vanilla
executable = /home/spxfp1/opt/lalsuite/lalinference_o2_phenomHM/bin/cbcBayesPostProc.py
arguments = " --bci $(macrobci) --skyres 0.5 --email greenr10@cardiff.ac.uk --snr $(macrosnr) --outpath $(macrooutpath) --archive $(macroarchive) $(macroargument0) $(macroargument1) "
request_memory = 2000
getenv = True
accounting_group = ligo.sim.o2.cbc.pe.lalinference
log = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_50_mode_PhenomPv2_inc_0.0_M90/PM90/lalinferencenest/IMRPhenomDthreePointFivePN/lalinference_pipeline-1413ca3e-6d29-11e7-a3af-002590fc7bee.log
error = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_50_mode_PhenomPv2_inc_0.0_M90/PM90/lalinferencenest/IMRPhenomDthreePointFivePN/log/resultspage-$(cluster)-$(process).err
output = /home/c1572221/Summer-project/inference-from-frames/GW150914_like_SNR_50_mode_PhenomPv2_inc_0.0_M90/PM90/lalinferencenest/IMRPhenomDthreePointFivePN/log/resultspage-$(cluster)-$(process).out
notification = never
queue 1
