universe = vanilla
executable = /home/spxfp1/opt/lalsuite/lalinference_o2_phenomHM/bin/cbcBayesPostProc.py
arguments = " --archive $(macroarchive) --snr $(macrosnr) --skyres 0.5 --outpath $(macrooutpath) --email greenr10@cardiff.ac.uk $(macroargument0) $(macroargument1) "
request_memory = 2000
getenv = True
accounting_group_user = rhys.green
accounting_group = ligo.sim.o2.cbc.pe.lalinference
log = /home/c1572221/Summer-project/inference-from-frames/BAM_q8a0_fix_scale_SNR_25_mode_HM_inc_0.0_M27/M27/lalinferencenest/IMRPhenomDthreePointFivePN/lalinference_pipeline-5b130144-67b5-11e7-a0c9-002590fc7bee.log
error = /home/c1572221/Summer-project/inference-from-frames/BAM_q8a0_fix_scale_SNR_25_mode_HM_inc_0.0_M27/M27/lalinferencenest/IMRPhenomDthreePointFivePN/log/resultspage-$(cluster)-$(process).err
output = /home/c1572221/Summer-project/inference-from-frames/BAM_q8a0_fix_scale_SNR_25_mode_HM_inc_0.0_M27/M27/lalinferencenest/IMRPhenomDthreePointFivePN/log/resultspage-$(cluster)-$(process).out
notification = never
queue 1
