universe = vanilla
executable = /home/spxfp1/opt/lalsuite/lalinference_o2_phenomHM/bin/lalapps_nest2pos
arguments = " --pos $(macropos) $(macroargument0) $(macroargument1) $(macroargument2) $(macroargument3) "
getenv = True
accounting_group_user = rhys.green
accounting_group = ligo.sim.o2.cbc.pe.lalinference
log = /home/c1572221/Summer-project/inference-from-frames/BAM_q8a0_fix_scale_SNR_25_mode_HM_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/lalinference_pipeline-41cf1ac8-6ad6-11e7-b548-002590fc7bee.log
error = /home/c1572221/Summer-project/inference-from-frames/BAM_q8a0_fix_scale_SNR_25_mode_HM_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/log/merge-$(cluster)-$(process).err
output = /home/c1572221/Summer-project/inference-from-frames/BAM_q8a0_fix_scale_SNR_25_mode_HM_inc_0.0_M45/M45/lalinferencenest/IMRPhenomDthreePointFivePN/log/merge-$(cluster)-$(process).out
notification = never
queue 1
